### PR TITLE
ProofTrace: Modern Proof Steps Recording for HOL Light

### PR DESCRIPTION
**Pull request by spolu**
This PR proposes ProofTrace, a new proof step extraction toolchain that is meaningfully more lightweight than Proofrecording or HolStep as it is minimal in size (only 171 lines in `fusion.ml`) and entirely written in OCaml (which makes it easier to install and operate).

I'd recommend removing Proofrecording which is dysfunctional with modern revisions of HOL Light but will leave that decision to you!

Obviously happy to iterate on the content of that PR!

### CODE REVIEW

**Comment by jrh13** [comment]
This looks really nice, thanks! I'll try it out and all being well I'll merge it in soon.

**Comment by spolu** [comment]
Happy to tweak things based on your feedback 👍

**Comment by jrh13** [comment]
As you'll see I merged it in as is --- all very nice! One very minor thing: can I add an official copyright line to the README like this, or whatever variant you prefer?

  (c) Copyright Stanislas Polu 2019

 I think something like this for each subdirectory is needed for the debian packaging legalities.

**Comment by spolu** [comment]
@jrh13 thanks! wilco.

**Pull request merged**
